name: "Upload SARIF"

# Run workflow each time code is pushed to your repository and on a schedule.
# The scheduled workflow runs every Thursday at 15:45 UTC.
on:
  push:
  schedule:
    - cron: '45 15 * * 4'

jobs:
  test1:
      runs-on: self-hosted
      steps:
       - name: home directory
         run: echo $HOME
  build:
    runs-on: self-hosted
    steps:
      - name: Build Yocto
        run: ls $HOME/build/raspberrypi
        #source sources/poky/oe-init-build-env .
        #bitbake core-image-minimal
      
  sarif:
    runs-on: self-hosted
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      # This step checks out a copy of your repository.
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: build/cve-output
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: my-analysis-tool
      - name: Upload artifacts
        run: ls $HOME/build/raspberrypi/build/tmp
